drop table if exists `DAY_SHEET`;
drop table if exists `WEEK_SHEET`;
drop table if exists `EMPLOYEE_PROJECT`;
drop table if exists `PROJECT`;
drop table if exists `EMPLOYEE`;
drop table if exists `MANAGER`;
drop table if exists `USER`;

CREATE TABLE `USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` date NOT NULL,
  `EMAIL` varchar(64) DEFAULT NULL,
  `ENABLE` char(1) NOT NULL,
  `EXPIRED` char(1) NOT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `ORGANIZATION` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(64) NOT NULL,
  `ROLE` varchar(255) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_lb5yrvw2c22im784wwrpwuq06` (`USERNAME`)
);

CREATE TABLE `MANAGER` (
  `MANAGER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MANAGER_ID`)
);
ALTER TABLE `MANAGER`
ADD CONSTRAINT `FK_75nae2bl7nv6lxyo7cawl09yp` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);

CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MANAGER_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`)
);
ALTER TABLE `EMPLOYEE`
ADD CONSTRAINT `FK_pahqxqqbjnk7q2759k4ogtusb` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `EMPLOYEE`
ADD CONSTRAINT `FK_slgfbmxe6gqdcw80b5gvn16ye` FOREIGN KEY (`MANAGER_ID`) REFERENCES `MANAGER` (`MANAGER_ID`);

CREATE TABLE `PROJECT` (
  `PROJECT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_DATE` date NOT NULL,
  `PROJECT_NAME` varchar(255) NOT NULL,
  `START_DATE` date NOT NULL,
  `MANAGER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PROJECT_ID`)
);
ALTER TABLE `PROJECT`
ADD CONSTRAINT `FK_a6wymvjew531cyqny7p941d3n` FOREIGN KEY (`MANAGER_ID`) REFERENCES `MANAGER` (`MANAGER_ID`);

CREATE TABLE `EMPLOYEE_PROJECT` (
  `PROJECT_ID` bigint(20) NOT NULL,
  `EMPLOYEE_ID` bigint(20) NOT NULL
);
ALTER TABLE `EMPLOYEE_PROJECT`
ADD CONSTRAINT `FK_6ckdxfsp1h3865760mx92t8ga` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`);
ALTER TABLE `EMPLOYEE_PROJECT`
ADD CONSTRAINT `FK_aof2p6b7mc9y0wuqrd7k4hykb` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);

CREATE TABLE `WEEK_SHEET` (
  `WEEK_SHEET_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `APPROVED_IND` char(1) NOT NULL,
  `START_DATE` date NOT NULL,
  `SUBMITTED_IND` char(1) NOT NULL,
  `TOTAL_HOUR` int(11) NOT NULL,
  `EMPLOYEE_ID` bigint(20) DEFAULT NULL,
  `PROJECT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`WEEK_SHEET_ID`)
);
ALTER TABLE `WEEK_SHEET`
ADD CONSTRAINT `FK_mh3pkfctlwjkkimkxftkk3kj5` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
ALTER TABLE `WEEK_SHEET`
ADD CONSTRAINT `FK_s63id264s3debrd4ev3p1gd6d` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`);

CREATE TABLE `DAY_SHEET` (
  `DAY_SHEET_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL,
  `HOUR` int(11) NOT NULL,
  `WEEK_SHEET_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DAY_SHEET_ID`)
);
ALTER TABLE `DAY_SHEET`
ADD CONSTRAINT `FK_8paxduno57iw5pbscnvlydac` FOREIGN KEY (`WEEK_SHEET_ID`) REFERENCES `WEEK_SHEET` (`WEEK_SHEET_ID`);